# options for analysis running
run:
  modules-download-mode: mod
linters-settings:
  funlen:
    lines: 300
    statements: 300
  gocyclo:
    min-complexity: 40
  dupl:
    threshold: 150
  misspell:
    locale: US
  lll:
    line-length: 190
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - whyNoLint
      - wrapperFunc

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl

issues:
  exclude-rules:
    - text: "Error return value of "
      linters:
        - errcheck
    - text: "parameter 'name' seems to be unused"
      linters:
        - revive
    - text: "`name` is unused"
      linters:
        - unparam
    - text: "type `typedDesc` is unused"
      linters:
        - unused
    - text: "func `pushMetric` is unused"
      linters:
        - unused
    - text: "mustNewConstMetric` is unused"
      linters:
        - unused
